apiVersion: 1
datasources:
  - id: 1
    uid: "bf7q9ieu9l2bkd"
    orgId: 1
    name: "nodered-api"
    type: "yesoreyeram-infinity-datasource"
    url: "http://nodered:1880/api/v1/"
    basicAuth: false
    basicAuthUser: ""
    isDefault: true
    jsonData:
      global_queries: []
      pdcInjected: false
    readOnly: false
    apiVersion: ""
    